site/ko/README.md

Update docs-l10n repo. link in README.md
Thanks.

KO: Update docs-l10n repo. link in README.md

---

CODEOWNERS

For pull request notifications

Initial GitHub codeowners file

---

site/vi/REVIEWERS

Hello,
I want to add myself to the reviewer list for the Vietnamese translations. Besides, I will also participate in the translation. Please consider this pull request from me.
Ps: How I can access **[this spreadsheet](https://docs.google.com/spreadsheets/d/1Qr104JJEJluj2Hg0kFuY74MhAXMYjDWVyVztZstwdzU/edit#gid=0)** is used for tracking the progress of Vietnamese translation?
I realize that the contributors have been active since October 2019, are they still active?
Kindly regards,
Duy-Thanh Doan

[vi] Request to be added as reviewer

---

site/ko/REVIEWERS

I would like to be added as a reviewer for Korean document translations. I will try my best to contribute by reviewing open PRs as well as newly uploaded translations. Thank you!

[KO] Request to be added as reviewer

---

site/vi/README.md
site/vi/tutorials/keras/overfit_and_underfit.ipynb

Migrate https://github.com/tensorflow/docs/pull/1118 by @anniehiehie 
CLA signed in that PR

[vi] Overfitting & Underfitting

---

site/ko/tutorials/keras/text_classification_with_hub.ipynb

Change tfds.load() to new TFDS subsplit API
And update several commits since Oct 22, 2019
Apply new TFDS subsplit API:
```
train_data, validation_data, test_data = tfds.load(
name="imdb_reviews", 
split=('train[:60%]', 'train[60%:]', 'test'),
as_supervised=True)
```
Add import:
```
!pip install tensorflow-hub
!pip install tfds-nightly
```
Update datasets link
```
IMDB 데이터셋은 [imdb reviews](https://www.tensorflow.org/datasets/catalog/imdb_reviews) 또는 [텐서플로 데이터셋](https://www.tensorflow.org/datasets)(TensorFlow datasets)에 포함되어 있습니다. ...
```
Remove sigmoid func
```
model.add(tf.keras.layers.Dense(1))
...
model.compile(optimizer='adam',
loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
metrics=['accuracy'])
```
Running in colab is ok.
Thanks!

[KO]: Fix error tfds.load()

---

site/ar/REVIEWERS

With this pull request, I am adding myself as a reviewer and will start to translate the documentation into Arabic.

Become a reviewer of tensorflow Arabic documentation 

---

site/ar/REVIEWERS

Add baheytharwat as a reviewer to site/ar

Update REVIEWERS - site/ar

---

site/zh-cn/tutorials/distribute/keras.ipynb

The notebook is updated using [nb_code_sync.py](https://github.com/tensorflow/docs-l10n/blob/master/tools/translation/nb_code_sync.py) tools.
```shell
docs-l10n $ python tools/translation/nb_code_sync.py site/zh-cn/tutorials/distribute/keras.ipynb --site_root tensorflow_docs_path/site/en --src tensorflow_docs_path/docs/site/en/tutorials/distribute/keras.ipynb
```
I don't know whether this is the right way to fix this problem.

zh-cn: fixing zh-cn/tutorials/distribute/keras.ipynb using nb_code_sync

---

site/ar/tutorials/quickstart/advanced.ipynb

Adds arabic translation of tutorials/quickstart/advanced notebook

[MRG] Add Arabic translation of tutorials/quickstart/advanced notebook

---

site/zh-cn/tutorials/keras/save_and_load.ipynb

Some contents, especially about SavedModel, are updated in this notebook, which requires additional review for translation.

zh-cn: fixing tutorials/keras/save_and_load.ipynb using nb_code_sync

---

site/zh-cn/REVIEWERS

With this pull request, I am adding myself as a reviewer and will start to translate the documentation into zh-cn.

[zh-cn] add reviewer

---

site/zh-cn/datasets/add_dataset.md

Translated https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md
Thanks for review!

zh-CN: translated datasets/add_dataset.md

---

site/zh-cn/tutorials/generative/style_transfer.ipynb

While fixing the notebook using `nb_code_sync`, this pull request also added the translation on some newly added parts like `Fast Style Transfer using TF-Hub`, which need additional translate review.

zh-CN: fixing zh-cn/tutorials/generative/style_transfer.ipynb using nb_code_sync

---

site/zh-cn/tutorials/distribute/multi_worker_with_keras.ipynb

Fixing zh-cn/tutorials/distribute/multi_worker_with_keras.ipynb using `nb_code_sync`

zh-cn: fixing zh-cn/tutorials/distribute/multi_worker_with_keras.ipynb using nb_code_sync

---

site/zh-cn/README.md
site/zh-cn/js/guide/node_in_cloud.md

Add a new translation file `site/zh-cn/js/guide/node_in_cloud.md`.
[Source file](https://github.com/tensorflow/tfjs-website/blob/master/docs/guide/node_in_cloud.md)

[zh-cn] Add js/guide/node_in_cloud.md

---

site/ja/guide/create_op.md

Original Document:
https://github.com/tensorflow/docs/blob/master/site/en/guide/create_op.md

JA: translation guide/create_op

---

site/ko/guide/gpu.ipynb

"가장" -> "가상"
[en](https://github.com/tensorflow/docs/blob/33f62e328c3a6ca7e14823cd03c483b7a344e70e/site/en/guide/gpu.ipynb#L397)
Thanks

[KO] Update one word in gpu.ipynb

---

site/it/community/contribute/code.md

[it] community-contribute-code.md

---

site/ar/README.md

This change clarifies to new contributors that they need to add their github usernames to REVIEWERS via a pull request.

[ar] Add instructions on how to join the community

---

site/vi/README.md
site/vi/REVIEWERS
site/vi/tutorials/keras/classification.ipynb
site/vi/tutorials/keras/overfit_and_underfit.ipynb
site/vi/tutorials/quickstart/advanced.ipynb
site/vi/tutorials/quickstart/beginner.ipynb

Hi Billy,
I have a question above docs@tensorflow.org list, you can see **[here](https://groups.google.com/a/tensorflow.org/g/docs/c/m1FDWWTBagI/m/XhSabJEIAgAJ)**. It is an opinion of mine, if this is supported, I will update it at this section before merging.

[VI] Update README

---

site/ko/tutorials/distribute/save_and_load.ipynb
site/ko/tutorials/keras/text_classification_with_hub.ipynb

Fix for #184.
- Correct some typos in translation.
- Update by nbfmt and nb_code_syn.
- Check with Colab.
Thanks

[KO]: update site/ko/tutorials/distribute/save_and_load.ipynb

---

site/ja/tutorials/text/text_classification_rnn.ipynb

I updated an outdated notebook. The original document is https://github.com/tensorflow/docs/blob/master/site/en/tutorials/text/text_classification_rnn.ipynb
See also: https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!msg/docs-ja/xDXiJS1E7UU/Aq8c3YpdAQAJ

[JA] Update site/ja/tutorials/text/text_classification_rnn.ipynb

---

site/ko/tutorials/estimator/keras_model_to_estimator.ipynb

Uploaded translation of tutorials/estimator/keras_model_to_estimator.ipynb

[KO] Translation of keras_model_to_estimator.ipynb

---

site/zh-cn/tutorials/keras/text_classification_with_hub.ipynb

`nb_code_sync` and `nbfm` the `text_classification_with_hub.ipynb`.

zh-cn: nb_code_sync tutorials/keras/text_classification_with_hub.ipynb

---

site/ja/tutorials/text/word_embeddings.ipynb

Update of an outdated notebook. The original document is
https://github.com/tensorflow/docs/blob/master/site/en/tutorials/text/word_embeddings.ipynb
See also: https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!msg/docs-ja/xDXiJS1E7UU/Aq8c3YpdAQAJ

[JA] Update site/ja/tutorials/text/word_embeddings.ipynb

---

site/zh-cn/tensorboard/scalars_and_keras.ipynb

translate https://github.com/tensorflow/tensorboard/blob/master/docs/scalars_and_keras.ipynb

zh-CN: Create scalars_and_keras.ipynb

---

site/ja/lite/microcontrollers/library.md

Original Document:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/microcontrollers/library.md

JA: Add ja/lite/microcontrollers/library.md

---

site/ko/tutorials/generative/style_transfer.ipynb

[KO] Update style_transfer.ipynb

---

tools/snapshot-source.sh

Script to create a snapshot of English source docs for all TensorFlow projects (and subsites).
Usage: `./tools/source-snapshot.sh [-c]`
Will use to test GitLocalize integration.
Example: https://github.com/lamberta/tf-docs-l10n/pull/7

snapshot-source script

---

site/ko/tutorials/generative/adversarial_fgsm.ipynb

Uploaded translation of tutorials/generative/adversarial_fgsm.ipynb

[KO] Translation of adversarial_fgsm.ipynb

---

site/zh-cn/tensorboard/graphs.ipynb

translate https://github.com/tensorflow/tensorboard/blob/master/docs/graphs.ipynb

zh-CN: translate graphs.ipynb

---

site/en-snapshot/README.md
site/en-snapshot/addons/tutorials/networks_seq2seq_nmt.ipynb
site/en-snapshot/community/contribute/docs.md
site/en-snapshot/guide/autodiff.ipynb
site/en-snapshot/guide/concrete_function.ipynb
site/en-snapshot/guide/function.ipynb
site/en-snapshot/guide/keras/custom_layers_and_models.ipynb
site/en-snapshot/guide/keras/save_and_serialize.ipynb
site/en-snapshot/guide/keras/train_and_evaluate.ipynb
site/en-snapshot/guide/migrate.ipynb
site/en-snapshot/guide/profiler.md
site/en-snapshot/guide/ragged_tensor.ipynb
site/en-snapshot/guide/saved_model.ipynb
site/en-snapshot/guide/tpu.ipynb
site/en-snapshot/guide/variable.ipynb
site/en-snapshot/js/tutorials/setup.md
site/en-snapshot/lite/convert/python_api.md
site/en-snapshot/lite/performance/hexagon_delegate.md
site/en-snapshot/lite/performance/post_training_float16_quant.ipynb
site/en-snapshot/lite/performance/post_training_integer_quant.ipynb
site/en-snapshot/lite/performance/post_training_quant.ipynb
site/en-snapshot/model_optimization/guide/pruning/comprehensive_guide.ipynb
site/en-snapshot/model_optimization/guide/quantization/training.md
site/en-snapshot/tfx/tutorials/data_validation/tfdv_basic.ipynb
site/en-snapshot/tfx/tutorials/tfx/components_keras.ipynb
site/en-snapshot/tfx/tutorials/transform/census.ipynb
site/en-snapshot/tutorials/distribute/multi_worker_with_keras.ipynb
site/en-snapshot/tutorials/generative/cvae.ipynb
site/en-snapshot/tutorials/load_data/images.ipynb
site/en-snapshot/tutorials/structured_data/time_series.ipynb

Projects and last commit:
- tensorflow/addons: https://github.com/tensorflow/addons/commit/a26a24d097e995e5bda994c911b75eac1a009c32
- tensorflow/agents: https://github.com/tensorflow/agents/commit/92efe8c60fa4bb9521107c1788f9aaa3cd332ecb
- tensorflow/datasets: https://github.com/tensorflow/datasets/commit/8b6a5479978d6a5813b4c5384d13e54ff363e0be
- tensorflow/docs: https://github.com/tensorflow/docs/commit/0d13617fbe162a95da7c6930aa69c997a9d62bd8
- tensorflow/federated: https://github.com/tensorflow/federated/commit/5815325f1c7ded17df868e25f1ff74cec170f7e1
- tensorflow/graphics: https://github.com/tensorflow/graphics/commit/e397941782fc5d754c9648f0442a2c9c262c0f84
- tensorflow/hub: https://github.com/tensorflow/hub/commit/74ebebd841cec144601da7d7b0dac60638f1be73
- tensorflow/hub: …

Source snapshot: Tue Jun  2 13:43:08 PDT 2020

---

site/ja/CONTRIBUTING.md
site/ja/README.md

This PR contains following changes.
- Add `community` directory to do not translate
- Fix link to docs-l10n

[JA] Update README.md and  CONTRIBUTING.md

---

tools/nb_code_sync.py

Surprisingly, some cells doesn't have cell id. :(
So, I just want to check if it's exist and reset cell id to blank.
Thanks.

Add cell id checking to avoid runtime error

---

site/ko/guide/function.ipynb
site/ko/guide/migrate.ipynb
site/ko/tutorials/images/segmentation.ipynb
site/ko/tutorials/keras/text_classification_with_hub.ipynb

Update notebooks for #184 
* migrate.ipynb
* function.ipynb
* segmentation.ipynb
* text_classification_with_hub.ipynb
nbfmt & nb_code_sync & colab checked!
Thanks

[KO] update out-of-sync notebooks

---

site/ru/REVIEWERS

Added myself as Russian reviewer (@ilyaspiridonov)

Add ilyaspiridonov as RU reviewer

---

site/ko/guide/function.ipynb
site/ko/guide/migrate.ipynb
site/ko/tutorials/images/segmentation.ipynb
site/ko/tutorials/keras/text_classification_with_hub.ipynb
site/ko/tutorials/text/text_generation.ipynb

nbfmt all the things

---

site/it/community/contribute/index.md

[it] community-contribute-index.md

---

site/it/README.md
site/it/tutorials/customization/basics.ipynb

Taking back PR #93 with the comments done by @codeadmin-peritiae 
If there are no other feedbacks we can approve this one and close #93

it - tutorial-customization-basics translation

---

site/zh-cn/tutorials/images/cnn.ipynb

Fixed translation error in line 399:"for another: '队友另一种' -> '对于另一种'

Fixed translation error

---

.github/workflows/bot-pr-fix.yaml
tools/ci/utils.sh

Tested in https://github.com/lamberta/tf-docs-l10n/pull/49

Add nblint --fix workflow for PRs

---

.github/workflows/bot-nightly.yaml

Workflow file tested [here](https://github.com/lamberta/tf-docs-l10n/runs/1103129990?check_suite_focus=true) (and other runs) and added [this commit](https://github.com/lamberta/tf-docs-l10n/commit/f7c80ba336053a5c26bc44f4fd126bb6d68a5592).

Add nightly bot workflow to snapshot source.

---

site/zh-cn/tutorials/images/segmentation.ipynb

Using [nb_code_sync](https://github.com/tensorflow/docs/blob/master/tools/nb_code_sync.py) and [nbfmt](https://github.com/tensorflow/docs/blob/master/tools/nbfmt.py) to sync and format the segmentation.ipynb.

zh-cn: fixing zh-cn/tutorials/images/segmentation.ipynb using nb_code_sync

---

site/ja/lite/performance/post_training_integer_quant.ipynb

Original Document:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/performance/post_training_integer_quant.ipynb

JA: Add ja/lite/g3doc/performance/post_training_integer_quant.ipynb

---

site/ru/guide/keras/custom_layers_and_models.ipynb

Pull request #1433 from tensorflow/docs. Closed it there

RU: Translation for guide/keras/custom_layers_and_models.ipynb

---

site/pt-br/tutorials/load_data/numpy.ipynb

tutorials/load_data/numpy in portuguese

PT: load numpy data

---

tools/ci/utils.sh

Temp fix. But lists files that were also modified on master.

Fix get_changed_files

---

site/it/tutorials/customization/custom_layers.ipynb

Italian translation for tutorials/customization/custom_layers.ipynb

[IT] translation for tutorials/customization/custom_layers.ipynb

---

site/zh-cn/tensorboard/fairness-indicators.md

Update the colab link.

---

site/pt-br/tutorials/keras/text_classification.ipynb

Corrige a expressão "do bando de dados" para "da base de dados"

Corrige expressão  "do bando de dados"

---

site/zh-cn/guide/gpu.ipynb

Changed the imports of all the experimental to the stable.

Updated to stable from experimental

---

site/ko/lite/performance/hexagon_delegate.md

Update incorrect version number in the documentation of hexagon delegate.

Update incorrect version

---

CODEOWNERS

Update codeowners for notifications

---

site/ja/guide/gpu.ipynb

Update_gpu with stable versions from experimental

Update_gpu with stable versions

---

site/es-419/guide/keras/custom_callback.ipynb

Rename `lr` to `learning_rate`

Rename lr to learning_rate

---

site/ja/js/tutorials/setup.md
site/ko/js/tutorials/setup.md
site/zh-cn/js/tutorials/setup.md

Expandable code samples are not properly shown in ja, ko, and zh-cn languages.

Fix expandable code sample sections in JS setup

---

site/zh-cn/tutorials/structured_data/feature_columns.ipynb

nbcp site/{en-snapshot,zh-cn}/tutorials/structured_data/feature_columns.ipynb
git add -p
git commit -m
Tested: in colab.

nbcp feature_columns.ipynb

---

site/zh-cn/tutorials/structured_data/imbalanced_data.ipynb

An entity was in code. Changed to use the greater than symbol

fixed greater-than entity to symbol

---

site/zh-cn/guide/distributed_training.ipynb

* Copied code cells from `en` notebook
* Deleted Estimator section from `zh-cn` (was missing from `en`)
Tested in colab.

Refresh `zh-cn/guide/distributed_training`

---

site/zh-cn/guide/data_performance.ipynb

This PR fixes the greater-than sign in a code cell in the tf.data API guide. This should fix build errors in Colab.

Fix greater-than sign in the tf.data API guide

---

site/zh-cn/guide/keras/transfer_learning.ipynb

nbcp transfer_learning.ipynb
Tested in colab.

nbcp transfer_learning.ipynb

---

site/zh-cn/hub/tutorials/cropnet_cassava.ipynb

nbcp cropnet_cassava.ipynb
Tested: colab

nbcp cropnet_cassava.ipynb

---

.github/workflows/bot-pr-fix.yaml
site/ja/guide/autodiff.ipynb

Fix actions
