tensorflow/docs-l10n

site/ko/README.md
Applied minor edits to README primarily to clarify the "do not translate" portion of the guideline.
=> [KO] Clarify translation guideline

.github/workflows/ci.yaml, README.md
Auto-format notebooks using `nbfmt.py --ignore_warn`. This GitHub Action is triggered on push and will auto-add a commit by @tfdocsbot to the submitted pull request branch.
Tested here: https://github.com/lamberta/tf-docs-l10n/pull/4 ([actions log](https://github.com/lamberta/tf-docs-l10n/actions))
Will need to watch for how CLA bot reacts 🤖
Ref: https://github.com/tensorflow/docs-l10n/issues/128
=> Add CI for nbfmt

.github/workflows/ci.yaml
Sticking with what GitHub Actions is good at: pass/fail tests. Auto-commits would be nice, but adds complexity and this is enough to let contributors know there's more work to be done.
Tested:
- example good run: https://github.com/lamberta/tf-docs-l10n/runs/549994932
- example bad run: https://github.com/lamberta/tf-docs-l10n/runs/549999385
=> Add nbfmt to GitHub CI tests

site/ja/lite/convert/python_api.md
Update of an outdated document. See also https://github.com/tensorflow/docs-l10n/issues/145
The original document is https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/convert/python_api.md
=> [JA] Update site/ja/lite/convert/python_api.md

.github/workflows/ci.yaml
Here's a test pull request: https://github.com/lamberta/tf-docs-l10n/pull/9
Can see the (intentional) lint warning output [here](https://github.com/lamberta/tf-docs-l10n/pull/9/checks?check_run_id=801481179).
=> Add nblint to GitHub Actions CI

.gitlocalize.yml
Enable GitLocalize config option that runs translated notebooks through nbfmt.py
=> Enable postprocess_jupyter_notebooks_with_nbfmt_py (GitLocalize config)

.github/labeler.yml, .github/workflows/ci.yaml, .github/workflows/label-lgtm.yaml
This replaces the auto-label functionality that @tfdocsbot currently provides. It's hopefully more maintainable than my own personal bot 🤖
It uses `actions/labeler@v2` to apply language labels based on directory.
And it adds the "lgtm" label to indicate *community approval* (not maintainer approval) through a pull request approval or a comment that contains "lgtm".
Tested here: https://github.com/lamberta/tf-docs-l10n/pull/14
=> Add auto-label workflow to GitHub Actions

.github/workflows/ci.yaml
Require all submitted translation docs have a counterpart file in the `site/en-snapshot/` directory.
Tested in https://github.com/lamberta/tf-docs-l10n/pull/29
=> Add CI check that translation source exists

.github/workflows/bot-label-lgtm.yaml
Auto-apply label to triage PRs that have been reviewed in [GitLocalize](https://gitlocalize.com/tensorflow/docs-l10n).
Tested in https://github.com/lamberta/tf-docs-l10n/pull/36
cc: @ilyaspiridonov
=> Auto-label vendor reviewed translations

site/zh-cn/guide/advanced_autodiff.ipynb, site/zh-cn/guide/checkpoint.ipynb, site/zh-cn/guide/data_performance.ipynb
Found with `nblint`:
```
python3 -m tensorflow_docs.tools.nblint \
--styles=tensorflow,tensorflow_docs_l10n \
--arg=repo:tensorflow/docs-l10n \
site/!(en-snapshot)
```
=> nblint fixes for site path

tools/snapshot-source.sh
Useful for setting up a nightly job and don't want a commit history full of timestamp changes.
=> snapshot-source: Ignore commit if no docs changes.

site/ko/tutorials/keras/text_classification_with_hub.ipynb
`NOT AVAILABLE` is not translated to Korean.
So I would like to refer to main page and apply the translation.
(main page : https://www.tensorflow.org/tutorials/keras/text_classification_with_hub)
CC : @rickiepark
=> [ko] text_classification_with_hub.ipynb tranlation

site/ko/tutorials/distribute/custom_training.ipynb
Fix little typo in `docs-l10n/site/ko/tutorials/distribute/custom_training.ipynb`
`tf.nn_scale_regularization_loss` -> `tf.nn.scale_regularization_loss`
=> Fix little typo in docs-l10n/site/ko/tutorials/distribute/custom_training.ipynb

.github/workflows/bot-pr-new.yaml
In this repo, the bot creates a message to format notebooks like https://github.com/tensorflow/docs-l10n/pull/498#issuecomment-808669230
In that message, I found a tiny typo and I fixed it.
=> Fix typo of ci message

site/ko/xla/architecture.md
Update broken image links in `site/ko/xla/architecture.md` following `site/ja/xla/architecture.md`.
You can see broken image links on this page(https://www.tensorflow.org/xla/architecture?hl=ko).
=> Fix broken image links

site/ko/tutorials/customization/custom_layers.ipynb
replaced tf.test.is_gpu_available with tf.config.list_physical_devices('GPU') to list the GPU devices.
=> Replacing the depreciated package

site/ja/tutorials/keras/classification.ipynb
An error occurred because `keras` was used instead of `tf.keras`. 
So I fixed that.
=> Fix from keras to tf.keras in a Japanese keras tutorial

site/zh-cn/lite/performance/gpu_advanced.md
Updated code changes inline with latest english document.
Fixes: https://github.com/tensorflow/tensorflow/issues/57039
=> Update code changes

site/zh-cn/hub/tutorials/spice.ipynb
This comes from tensorflow/hub, examples/colab/spice.ipynb.
Update is minor, but it's the fix for the notebook failure. Tested
locally.
=> Refresh `zh-cn/hub/tutorials/spice.ipynb`

.github/workflows/check-failed-notebooks.yml
Notebooks are currently tested on periodic basis (weekly or bi-weekly), and the lists of failing notebooks are stored at  ```https://storage.googleapis.com/tensorflow_docs/failed_notebooks/<lang>/failed_notebooks.txt``` ([example](https://storage.googleapis.com/tensorflow_docs/failed_notebooks/ja/failed_notebooks.txt))
This proposed GitHub Action will run weekly to update the in-repo reports like [this one ](https://github.com/tensorflow/docs-l10n/blob/master/site/ja/FAILURES.md) that include direct links to GitLocalize, Github and Colab for better visibility and easier fixing. 
The GHA will use an existing [script](https://github.com/tensorflow/docs-l10n/blob/master/tools/notebook-status.sh)
=> New Github Action to update the list of failed notebooks weekly

site/ja/tutorials/text/transformer.ipynb, site/zh-cn/tutorials/text/transformer.ipynb
Fixed the broken link for StarCraft units in line 92.
=> Fix broken link in `transformer.ipynb`
